apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: microservice-2 
spec: 
  selector: 
    matchLabels: 
      app: microservice-2 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: microservice-2 
    spec: 
      containers: 
      - name: microservice-2 
        imagePullPolicy: Never
        image: microservice-2:0.0.1
        ports: 
        - containerPort: 8080 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: microservice-2-service 
spec: 
  selector: 
    app: microservice-2 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 8080 
    nodePort: 30021
  type: NodePort 