apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: node-microservice-test 
spec: 
  selector: 
    matchLabels: 
      app: node-microservice-test
  replicas: 3 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: node-microservice-test 
    spec: 
      containers: 
      - name: node-microservice-test
        imagePullPolicy: Never
        image: dogenrwot/node-microservice-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: node-microservice-test

---
apiVersion: v1
kind: Service
metadata:
name: node-microservice-test
labels:
  app: node-microservice-test
spec:
ports:
  - port: 8000
    targetPort: 8000
selector:
  app: node-microservice-test
  tier: node-microservice-test
type: LoadBalancer