name: trigger jenkins job
on:
  push:
    branches: [ ft-jenkins-trigger ]
defaults:
  run:
    working-directory: devops
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: determine changed microservices
      id: getfile
      run: |
        chmod +x bin/changed.sh
        bin/changed.sh
    #    echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r $${{ github.sha }} | xargs)"
    # - name: echo the changed files
    #   run: |
    #     for i in $${{ steps.getfile.output.files }}; do 
    #       echo $i 
    #     done
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_URL }}
        user: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "stage-test"
