name: trigger jenkins job
on:
  push:
    branches: [ ft-jenkins-trigger ]
defaults:
  run:
    working-directory: devops
env:
  GIT_PREVIOUS_COMMIT: $(git rev-parse --short "HEAD^")
  GIT_COMMIT: $(git rev-parse --short HEAD)
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: determine changed microservices
      id: files
      uses: jitterbit/get-changed-files@v1
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_URL }}
        user: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "stage-test"
