name: trigger jenkins job
on:
  push:
    branches: [ ft-jenkins-trigger ]
defaults:
  run:
    working-directory: devops
env:
  GIT_PREVIOUS_COMMIT: $(git rev-parse --short "HEAD^")
  GIT_COMMIT: $(git rev-parse --short HEAD)
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: determine changed microservices
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff --name-only $${ env.GIT_PREVIOUS_COMMIT }} $${ env.GIT_COMMIT }} | sort -u | awk 'BEGIN {FS="/"} {print $1}' | uniq)"
    - name: echo the changed files
      run: |
        for i in $${{ steps.getfile.output.files }}; do 
          echo $i 
        done
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_URL }}
        user: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "stage-test"
